package com.proyectofinal.brainchis

import kotlin.random.Random

object BancoPreguntas {

    private val preguntas = listOf(
        //Matemáticas
        Pregunta("¿Cuánto es 5 + 5?", listOf("8", "10", "12", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 8 x 5?", listOf("40", "35", "45", "30"), 0, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un triángulo?", listOf("3", "4", "5", "6"), 0, "Matemáticas"),
        Pregunta("¿Cuál es la mitad de 50?", listOf("20", "25", "30", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 100 - 30?", listOf("60", "80", "70", "50"), 2, "Matemáticas"),
        Pregunta("¿Qué figura es redonda?", listOf("Cuadrado", "Círculo", "Triángulo", "Rombo"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 12 / 4?", listOf("2", "4", "3", "6"), 2, "Matemáticas"),
        Pregunta("¿Cuántos minutos tiene una hora?", listOf("100", "50", "30", "60"), 3, "Matemáticas"),
        Pregunta("El doble de 8 es...", listOf("16", "18", "14", "20"), 0, "Matemáticas"),
        Pregunta("¿Cuánto es 7 x 7?", listOf("49", "42", "56", "47"), 0, "Matemáticas"),
        Pregunta("¿Qué número es impar?", listOf("2", "4", "8", "7"), 3, "Matemáticas"),
        Pregunta("¿Qué número es par?", listOf("3", "5", "6", "9"), 2, "Matemáticas"),
        Pregunta("Una docena son...", listOf("10", "12", "20", "6"), 1, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un cuadrado?", listOf("4", "5", "3", "6"), 0, "Matemáticas"),
        Pregunta("Suma: 15 + 15", listOf("20", "25", "30", "35"), 2, "Matemáticas"),
        Pregunta("Resta: 20 - 8", listOf("10", "11", "13", "12"), 3, "Matemáticas"),
        Pregunta("¿Cuánto es 9 x 2?", listOf("18", "20", "16", "19"), 0, "Matemáticas"),
        Pregunta("Si tienes 3 manzanas y comes 1, quedan...", listOf("1", "3", "2", "0"), 2, "Matemáticas"),
        Pregunta("¿Cuál es mayor?", listOf("10", "50", "9", "49"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 10 x 10?", listOf("100", "1000", "20", "50"), 0, "Matemáticas"),
        Pregunta("¿Cuántas horas tiene un día?", listOf("12", "20", "24", "48"), 2, "Matemáticas"),
        Pregunta("La figura de 5 lados se llama...", listOf("Cuadrado", "Hexágono", "Pentágono", "Triángulo"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 6 x 3?", listOf("12", "18", "24", "16"), 1, "Matemáticas"),
        Pregunta("Suma: 50 + 50", listOf("90", "100", "110", "120"), 1, "Matemáticas"),
        Pregunta("¿Cuál es el número romano V?", listOf("1", "10", "5", "100"), 2, "Matemáticas"),
        //--- MATEMÁTICAS (BLOQUE 2) ---
        Pregunta("¿Cuánto es 20 + 20?", listOf("30", "40", "50", "60"), 1, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un rectángulo?", listOf("3", "4", "5", "6"), 1, "Matemáticas"),
        Pregunta("El doble de 10 es...", listOf("15", "20", "30", "100"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 3 x 3?", listOf("6", "9", "12", "33"), 1, "Matemáticas"),
        Pregunta("La mitad de 10 es...", listOf("2", "5", "4", "6"), 1, "Matemáticas"),
        Pregunta("¿Qué número sigue? 2, 4, 6, ...", listOf("7", "8", "9", "10"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 15 - 5?", listOf("5", "15", "10", "20"), 2, "Matemáticas"),
        Pregunta("Un metro tiene 100...", listOf("Metros", "Kilómetros", "Centímetros", "Litros"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 5 x 4?", listOf("15", "20", "25", "10"), 1, "Matemáticas"),
        Pregunta("¿Qué figura tiene 3 lados?", listOf("Cuadrado", "Círculo", "Triángulo", "Rombo"), 2, "Matemáticas"),
        Pregunta("Suma: 100 + 200", listOf("200", "300", "400", "500"), 1, "Matemáticas"),
        Pregunta("Resta: 50 - 25", listOf("25", "30", "15", "20"), 0, "Matemáticas"),
        Pregunta("¿Cuánto es 6 x 2?", listOf("10", "12", "14", "8"), 1, "Matemáticas"),
        Pregunta("¿Qué mide un reloj?", listOf("Peso", "Altura", "Tiempo", "Distancia"), 2, "Matemáticas"),
        Pregunta("¿Qué número es mayor?", listOf("100", "99", "101", "90"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 8 / 2?", listOf("2", "3", "4", "5"), 2, "Matemáticas"),
        Pregunta("La tercia de 9 es...", listOf("2", "3", "4", "6"), 1, "Matemáticas"),
        Pregunta("¿Cuántos días tiene una semana?", listOf("5", "6", "7", "8"), 2, "Matemáticas"),
        Pregunta("¿Cuántos meses tiene un año?", listOf("10", "11", "12", "14"), 2, "Matemáticas"),
        Pregunta("¿Qué número es menor?", listOf("5", "8", "2", "10"), 2, "Matemáticas"),
        Pregunta("Suma: 8 + 7", listOf("14", "15", "16", "13"), 1, "Matemáticas"),
        Pregunta("El triple de 3 es...", listOf("6", "9", "12", "3"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 10 - 7?", listOf("2", "3", "4", "1"), 1, "Matemáticas"),
        Pregunta("¿Qué usas para medir tu altura?", listOf("Báscula", "Metro", "Reloj", "Termómetro"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 4 x 4?", listOf("12", "14", "16", "20"), 2, "Matemáticas"),
        Pregunta("Figura que parece una pelota", listOf("Cubo", "Esfera", "Pirámide", "Cono"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 11 + 11?", listOf("20", "21", "22", "23"), 2, "Matemáticas"),
        Pregunta("Resta: 30 - 10", listOf("10", "20", "30", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 2 x 9?", listOf("16", "17", "18", "20"), 2, "Matemáticas"),
        Pregunta("¿Cuántos segundos tiene un minuto?", listOf("30", "45", "60", "100"), 2, "Matemáticas"),
        Pregunta("Suma: 6 + 6", listOf("10", "11", "12", "13"), 2, "Matemáticas"),
        Pregunta("¿Cuál es número par?", listOf("1", "3", "5", "8"), 3, "Matemáticas"),
        Pregunta("¿Cuál es número impar?", listOf("2", "4", "6", "9"), 3, "Matemáticas"),
        Pregunta("¿Cuánto es 40 + 10?", listOf("40", "50", "60", "30"), 1, "Matemáticas"),
        Pregunta("La mitad de 100 es...", listOf("40", "60", "50", "25"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 5 x 5?", listOf("20", "30", "35", "25"), 3, "Matemáticas"),
        Pregunta("¿Cuántas caras tiene un cubo?", listOf("4", "5", "6", "8"), 2, "Matemáticas"),
        Pregunta("Suma: 9 + 9", listOf("16", "17", "18", "19"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 20 / 2?", listOf("5", "10", "15", "2"), 1, "Matemáticas"),
        Pregunta("El número anterior a 20 es...", listOf("18", "21", "19", "22"), 2, "Matemáticas"),

        //Ciencias
        Pregunta("¿Cuál es el planeta rojo?", listOf("Tierra", "Marte", "Júpiter", "Venus"), 1, "Ciencias"),
        Pregunta("¿Qué respiran los humanos?", listOf("Oxígeno", "Helio", "Agua", "Carbón"), 0, "Ciencias"),
        Pregunta("¿El animal más grande del mundo?", listOf("Elefante", "Ballena Azul", "Tiburón", "Jirafa"), 1, "Ciencias"),
        Pregunta("¿Cuántas patas tiene una araña?", listOf("6", "4", "8", "10"), 2, "Ciencias"),
        Pregunta("El Sol es una...", listOf("Estrella", "Planeta", "Luna", "Cometa"), 0, "Ciencias"),
        Pregunta("¿Qué animal produce leche?", listOf("Vaca", "Gallina", "Pez", "Tortuga"), 0, "Ciencias"),
        Pregunta("¿Qué comen los herbívoros?", listOf("Carne", "Plantas", "Insectos", "Todo"), 1, "Ciencias"),
        Pregunta("¿Estado del hielo?", listOf("Líquido", "Sólido", "Gaseoso", "Plasma"), 1, "Ciencias"),
        Pregunta("¿Cuántos huesos tiene un adulto (aprox)?", listOf("100", "500", "206", "300"), 2, "Ciencias"),
        Pregunta("Órgano que bombea sangre", listOf("Pulmón", "Cerebro", "Corazón", "Estómago"), 2, "Ciencias"),
        Pregunta("¿Qué nos da luz natural?", listOf("Luna", "Sol", "Fuego", "Bombilla"), 1, "Ciencias"),
        Pregunta("Animal que vuela", listOf("Perro", "Gato", "Águila", "Elefante"), 2, "Ciencias"),
        Pregunta("Líquido vital para la vida", listOf("Refresco", "Aceite", "Agua", "Leche"), 2, "Ciencias"),
        Pregunta("El satélite de la Tierra es...", listOf("Sol", "Luna", "Marte", "Júpiter"), 1, "Ciencias"),
        Pregunta("Animal rey de la selva", listOf("Tigre", "León", "Mono", "Oso"), 1, "Ciencias"),
        Pregunta("¿Qué parte de la planta está bajo tierra?", listOf("Hoja", "Tallo", "Raíz", "Flor"), 2, "Ciencias"),
        Pregunta("Animal que vive en el agua", listOf("Pájaro", "Pez", "León", "Gato"), 1, "Ciencias"),
        Pregunta("¿Dónde digerimos la comida?", listOf("Estómago", "Corazón", "Pulmones", "Cerebro"), 0, "Ciencias"),
        Pregunta("Planeta con anillos", listOf("Marte", "Saturno", "Venus", "Mercurio"), 1, "Ciencias"),
        Pregunta("¿Qué animal pone huevos?", listOf("Perro", "Gato", "Gallina", "Vaca"), 2, "Ciencias"),
        Pregunta("La fórmula H2O es...", listOf("Sal", "Aire", "Oro", "Agua"), 3, "Ciencias"),
        Pregunta("¿Qué usamos para pensar?", listOf("Corazón", "Cerebro", "Hígado", "Riñón"), 1, "Ciencias"),
        Pregunta("El agua hierve a...", listOf("50°C", "80°C", "100°C", "200°C"), 2, "Ciencias"),
        Pregunta("¿Cuántos dientes de leche tenemos?", listOf("20", "32", "10", "50"), 0, "Ciencias"),
        Pregunta("Gas que exhalamos", listOf("Oxígeno", "Dióxido de Carbono", "Helio", "Nitrógeno"), 1, "Ciencias"),
        Pregunta("Animal que tiene trompa", listOf("Elefante", "Jirafa", "León", "Oso"), 0, "Ciencias"),
        Pregunta("¿Qué nos da calor?", listOf("Hielo", "Fuego", "Agua", "Viento"), 1, "Ciencias"),
        Pregunta("¿De dónde viene la lluvia?", listOf("Suelo", "Nubes", "Sol", "Luna"), 1, "Ciencias"),
        Pregunta("Animal que ladra", listOf("Gato", "Vaca", "Perro", "Pato"), 2, "Ciencias"),
        Pregunta("¿Qué parte del cuerpo usamos para ver?", listOf("Oídos", "Nariz", "Ojos", "Boca"), 2, "Ciencias"),
        Pregunta("¿Qué parte del cuerpo usamos para oír?", listOf("Ojos", "Oídos", "Manos", "Pies"), 1, "Ciencias"),
        Pregunta("El hielo es agua en estado...", listOf("Líquido", "Sólido", "Gaseoso", "Vapor"), 1, "Ciencias"),
        Pregunta("Animal que maúlla", listOf("Perro", "Pájaro", "Gato", "Ratón"), 2, "Ciencias"),
        Pregunta("¿Qué respiran los peces?", listOf("Aire", "Oxígeno del agua", "Tierra", "Fuego"), 1, "Ciencias"),
        Pregunta("¿Cuántas estaciones tiene el año?", listOf("2", "3", "4", "5"), 2, "Ciencias"),
        Pregunta("Estación donde hace frío", listOf("Verano", "Primavera", "Otoño", "Invierno"), 3, "Ciencias"),
        Pregunta("Estación donde hace calor", listOf("Invierno", "Otoño", "Verano", "Primavera"), 2, "Ciencias"),
        Pregunta("Fruta amarilla y curva", listOf("Manzana", "Plátano", "Uva", "Naranja"), 1, "Ciencias"),
        Pregunta("¿Qué sale de un volcán?", listOf("Agua", "Lava", "Hielo", "Flores"), 1, "Ciencias"),
        Pregunta("Animal que tiene cuello muy largo", listOf("Elefante", "Jirafa", "Caballo", "Tigre"), 1, "Ciencias"),
        Pregunta("¿Qué necesitan las plantas para vivir?", listOf("Coca-Cola", "Agua y Sol", "Oscuridad", "Jugo"), 1, "Ciencias"),
        Pregunta("El Sol sale por el...", listOf("Norte", "Sur", "Este", "Oeste"), 2, "Ciencias"),
        Pregunta("¿Qué cubre el cuerpo de las aves?", listOf("Pelo", "Escamas", "Plumas", "Piel"), 2, "Ciencias"),
        Pregunta("¿Qué cubre el cuerpo de los peces?", listOf("Pelo", "Escamas", "Plumas", "Ropa"), 1, "Ciencias"),
        Pregunta("Animal que da lana", listOf("Vaca", "Cerdo", "Oveja", "Caballo"), 2, "Ciencias"),
        Pregunta("¿Cuál es un ser vivo?", listOf("Piedra", "Árbol", "Mesa", "Coche"), 1, "Ciencias"),
        Pregunta("¿Cuál NO es un ser vivo?", listOf("Gato", "Planta", "Niño", "Juguete"), 3, "Ciencias"),
        Pregunta("¿Qué usamos para oler?", listOf("Boca", "Ojos", "Nariz", "Orejas"), 2, "Ciencias"),
        Pregunta("¿Qué usamos para saborear?", listOf("Lengua", "Dientes", "Labios", "Nariz"), 0, "Ciencias"),
        Pregunta("Animal que salta y es verde", listOf("Perro", "Rana", "Gato", "Vaca"), 1, "Ciencias"),
        Pregunta("¿Qué comen las vacas?", listOf("Carne", "Pasto", "Peces", "Insectos"), 1, "Ciencias"),
        Pregunta("Líquido blanco que bebemos", listOf("Agua", "Jugo", "Leche", "Aceite"), 2, "Ciencias"),
        Pregunta("¿Dónde viven los osos polares?", listOf("Desierto", "Selva", "Polo Norte", "Playa"), 2, "Ciencias"),
        Pregunta("El órgano que controla el cuerpo es...", listOf("Corazón", "Cerebro", "Estómago", "Hueso"), 1, "Ciencias"),
        Pregunta("¿Cuántas patas tiene un perro?", listOf("2", "4", "6", "8"), 1, "Ciencias"),
        Pregunta("Animal que vuela de noche", listOf("Águila", "Murciélago", "Pato", "Gallina"), 1, "Ciencias"),
        Pregunta("¿Qué es la Tierra?", listOf("Una estrella", "Un planeta", "Una luna", "Un cometa"), 1, "Ciencias"),
        Pregunta("¿De qué color es la sangre?", listOf("Azul", "Verde", "Roja", "Amarilla"), 2, "Ciencias"),
        Pregunta("¿Qué insecto hace miel?", listOf("Mosca", "Abeja", "Hormiga", "Mariposa"), 1, "Ciencias"),
        Pregunta("Animal más alto del mundo", listOf("Elefante", "Jirafa", "Oso", "León"), 1, "Ciencias"),
        Pregunta("¿Qué animal es 'Rey de la Selva'?", listOf("Tigre", "León", "Lobo", "Zorro"), 1, "Ciencias"),
        Pregunta("¿Qué protege nuestro cerebro?", listOf("Costillas", "Cráneo", "Piel", "Pelo"), 1, "Ciencias"),
        Pregunta("¿Qué usamos para caminar?", listOf("Manos", "Brazos", "Piernas", "Cabeza"), 2, "Ciencias"),
        Pregunta("La luna sale de...", listOf("Día", "Noche", "Tarde", "Mañana"), 1, "Ciencias"),
        Pregunta("¿Qué es un renacuajo?", listOf("Un pez", "Una rana bebé", "Un insecto", "Un pájaro"), 1, "Ciencias"),

        //Programación básica

        //Lógica Computacional y Conceptos Básicos
        Pregunta("¿Qué es un algoritmo?", listOf("Un ritmo musical", "Una serie de pasos ordenados", "Un virus de computadora", "Una pieza de hardware"), 1, "Programación básica"),
        Pregunta("¿Qué es un 'bug' en programación?", listOf("Una función rápida", "Un error en el código", "Un tipo de variable", "Un antivirus"), 1, "Programación básica"),
        Pregunta("El sistema binario usa solo los números...", listOf("1 y 2", "0 y 1", "0 y 9", "1 y 10"), 1, "Programación básica"),
        Pregunta("¿Qué significa 'debug' o 'depurar'?", listOf("Borrar todo el código", "Encontrar y arreglar errores", "Escribir código rápido", "Apagar la computadora"), 1, "Programación básica"),
        Pregunta("¿Qué es el Hardware?", listOf("Los programas", "La parte física que puedes tocar", "Internet", "Los datos"), 1, "Programación básica"),
        Pregunta("¿Qué es el Software?", listOf("El teclado y ratón", "La pantalla", "Los programas y aplicaciones", "Los cables"), 2, "Programación básica"),
        Pregunta("¿Qué hace un programador?", listOf("Repara computadoras", "Escribe instrucciones para la PC", "Vende celulares", "Instala internet"), 1, "Programación básica"),
        Pregunta("¿Cuál es un lenguaje de programación?", listOf("HTML", "Python", "English", "JPEG"), 1, "Programación básica"),
        Pregunta("¿Qué es una variable?", listOf("Un valor que cambia", "Un error fijo", "Una constante", "Un cable"), 0, "Programación básica"),
        Pregunta("En lógica, ¿qué valor es lo opuesto a TRUE?", listOf("YES", "FALSE", "NULL", "ERROR"), 1, "Programación básica"),
        Pregunta("¿Qué operador usas para sumar?", listOf("-", "*", "+", "/"), 2, "Programación básica"),
        Pregunta("¿Qué operador usas para multiplicar?", listOf("x", "*", "+", "#"), 1, "Programación básica"),
        Pregunta("¿Qué resultado da: NOT True?", listOf("True", "False", "Maybe", "Error"), 1, "Programación básica"),
        Pregunta("¿Qué es un bucle (loop)?", listOf("Un error fatal", "Una repetición de instrucciones", "Un botón de salida", "Un cable circular"), 1, "Programación básica"),
        Pregunta("¿Qué es el código fuente?", listOf("El texto escrito por el programador", "La contraseña del wifi", "El número de serie", "El nombre de la PC"), 0, "Programación básica"),
        Pregunta("La CPU es el ___ de la computadora.", listOf("Corazón", "Cerebro", "Pulmón", "Estómago"), 1, "Programación básica"),
        Pregunta("¿Qué es un diagrama de flujo?", listOf("Un dibujo artístico", "Una representación gráfica de un algoritmo", "Un mapa de carreteras", "Una foto de la PC"), 1, "Programación básica"),
        Pregunta("¿Qué forma representa el 'INICIO' en un diagrama?", listOf("Cuadrado", "Óvalo", "Rombo", "Triángulo"), 1, "Programación básica"),
        Pregunta("¿Qué forma representa una 'DECISIÓN' en un diagrama?", listOf("Círculo", "Rectángulo", "Rombo", "Flecha"), 2, "Programación básica"),
        Pregunta("¿Qué es la 'Sintaxis' en programación?", listOf("El color del código", "Las reglas de escritura del lenguaje", "La velocidad de la PC", "El nombre del programa"), 1, "Programación básica"),

        //Secuencias y Orden
        Pregunta("En una receta, ¿qué importa más?", listOf("El color del papel", "El orden de los pasos", "El nombre del chef", "La hora del día"), 1, "Programación básica"),
        Pregunta("Para lavarte los dientes, ¿qué va primero?", listOf("Enjuagarse", "Poner pasta al cepillo", "Cepillar", "Secarse"), 1, "Programación básica"),
        Pregunta("¿Qué pasa si alteras el orden de un algoritmo?", listOf("Nada", "Funciona mejor", "Puede fallar o dar otro resultado", "Se apaga la PC"), 2, "Programación básica"),
        Pregunta("Para plantar un árbol, el primer paso es...", listOf("Regar", "Hacer un agujero", "Poner la semilla", "Esperar"), 1, "Programación básica"),
        Pregunta("En la secuencia: 2, 4, 6, 8... ¿qué sigue?", listOf("9", "10", "11", "12"), 1, "Programación básica"),
        Pregunta("En la secuencia: A, B, C... ¿qué sigue?", listOf("E", "F", "D", "G"), 2, "Programación básica"),
        Pregunta("¿Qué instrucción va al final de un programa?", listOf("Inicio", "Fin", "Proceso", "Decisión"), 1, "Programación básica"),
        Pregunta("Para cruzar la calle, primero debes...", listOf("Correr", "Cerrar los ojos", "Mirar a ambos lados", "Saltar"), 2, "Programación básica"),
        Pregunta("Si 'A' es antes que 'B', ¿cuál va primero?", listOf("B", "A", "Ninguna", "Las dos"), 1, "Programación básica"),
        Pregunta("¿Cómo se lee un código generalmente?", listOf("De abajo a arriba", "De derecha a izquierda", "De arriba a abajo", "Aleatoriamente"), 2, "Programación básica"),
        Pregunta("Secuencia de luces del semáforo:", listOf("Verde, Amarillo, Rojo", "Rojo, Azul, Verde", "Amarillo, Verde, Rojo", "Verde, Rojo, Azul"), 0, "Programación básica"),
        Pregunta("Para enviar un correo, lo último es...", listOf("Escribir", "Dar clic en Enviar", "Poner el asunto", "Adjuntar archivo"), 1, "Programación básica"),
        Pregunta("Algoritmo para sumar 2+2:", listOf("Restar 2", "Multiplicar 2", "Sumar 2 y 2", "Dividir 2"), 2, "Programación básica"),
        Pregunta("En una pila de platos, ¿cuál lavas primero?", listOf("El de abajo", "El de arriba", "El del medio", "Cualquiera"), 1, "Programación básica"),
        Pregunta("Paso 1: Abrir puerta. Paso 2: ...", listOf("Cerrar puerta", "Entrar", "Salir volando", "Dormir"), 1, "Programación básica"),
        Pregunta("¿Qué es una secuencia lógica?", listOf("Pasos al azar", "Pasos con sentido y orden", "Pasos imposibles", "Pasos repetidos"), 1, "Programación básica"),
        Pregunta("Para ponerte zapatos, primero te pones...", listOf("Los calcetines", "Los zapatos", "Las agujetas", "El pantalón"), 0, "Programación básica"),
        Pregunta("Input -> Proceso -> ...", listOf("Inicio", "Output (Salida)", "Error", "Bucle"), 1, "Programación básica"),
        Pregunta("Secuencia: Mañana, Tarde, ...", listOf("Día", "Noche", "Mediodía", "Amanecer"), 1, "Programación básica"),
        Pregunta("¿Qué instrucción usarías para avanzar?", listOf("Girar", "Mover adelante", "Parar", "Saltar"), 1, "Programación básica"),

        //Condicionales
        Pregunta("¿Qué palabra clave inicia una condición?", listOf("Loop", "If (Si)", "For", "Print"), 1, "Programación básica"),
        Pregunta("SI llueve, ENTONCES...", listOf("Salgo a jugar", "Uso paraguas", "Riego las plantas", "Me pongo gafas de sol"), 1, "Programación básica"),
        Pregunta("SI el semáforo está rojo...", listOf("Avanzo", "Corro", "Me detengo", "Giro"), 2, "Programación básica"),
        Pregunta("¿Qué significa 'Else' (Sino)?", listOf("Lo que pasa si la condición es falsa", "Lo que pasa siempre", "El inicio del programa", "Un error"), 0, "Programación básica"),
        Pregunta("SI tengo hambre...", listOf("Duermo", "Corro", "Como algo", "Juego"), 2, "Programación básica"),
        Pregunta("SI batería < 15% ENTONCES...", listOf("Jugar más", "Cargar el celular", "Tomar fotos", "Nada"), 1, "Programación básica"),
        Pregunta("¿Cuál es un operador de comparación?", listOf("+", "-", "=", "> (Mayor que)"), 3, "Programación básica"),
        Pregunta("¿Qué devuelve una condición?", listOf("Un número", "Verdadero o Falso", "Una letra", "Un color"), 1, "Programación básica"),
        Pregunta("SI 5 > 3 ENTONCES...", listOf("Es Verdadero", "Es Falso", "Es un error", "Es igual"), 0, "Programación básica"),
        Pregunta("SI sacas 10 en el examen...", listOf("Repruebas", "Apruebas con honores", "Te castigan", "Nada"), 1, "Programación básica"),
        Pregunta("Un condicional sirve para...", listOf("Repetir cosas", "Tomar decisiones", "Guardar datos", "Dibujar"), 1, "Programación básica"),
        Pregunta("SI no estudias...", listOf("Sacas 10", "Aprendes mucho", "Probablemente repruebes", "Ganas un premio"), 2, "Programación básica"),
        Pregunta("SI x = 5 y sumas 1, x es...", listOf("4", "5", "6", "10"), 2, "Programación básica"),
        Pregunta("¿Qué pasa en el 'Else' de: SI es de día...?", listOf("Es de noche", "Hay sol", "Es temprano", "Es mediodía"), 0, "Programación básica"),
        Pregunta("Operador para 'igual a':", listOf(">", "<", "==", "!="), 2, "Programación básica"),
        Pregunta("Operador para 'diferente de':", listOf("==", "=", "!=", "<>"), 2, "Programación básica"),
        Pregunta("SI presionas el interruptor...", listOf("Se enciende la luz", "Sale agua", "Suena música", "Se abre la puerta"), 0, "Programación básica"),
        Pregunta("SI tienes sueño...", listOf("Corres", "Gritas", "Duermes", "Comes"), 2, "Programación básica"),
        Pregunta("La estructura IF-ELSE permite...", listOf("Un solo camino", "Dos caminos posibles", "Infinitos caminos", "Ningún camino"), 1, "Programación básica"),
        Pregunta("SI tocas fuego...", listOf("Te congelas", "Te quemas", "Te mojas", "Te ríes"), 1, "Programación básica"),

        //Pensamiento Algorítmico y Resolución de Problemas
        Pregunta("Descomponer un problema grande en pequeños se llama...", listOf("Descomposición", "Abstracción", "Patrón", "Algoritmo"), 0, "Programación básica"),
        Pregunta("Encontrar similitudes entre cosas es...", listOf("Descomposición", "Reconocimiento de patrones", "Programación", "Error"), 1, "Programación básica"),
        Pregunta("Ignorar detalles innecesarios se llama...", listOf("Descomposición", "Abstracción", "Atención", "Olvido"), 1, "Programación básica"),
        Pregunta("Crear pasos para resolver un problema es...", listOf("Diseño de algoritmos", "Dibujo", "Matemáticas", "Lectura"), 0, "Programación básica"),
        Pregunta("¿Cuál NO es parte del pensamiento computacional?", listOf("Abstracción", "Patrones", "Adivinanza", "Algoritmos"), 2, "Programación básica"),
        Pregunta("Para armar un rompecabezas, una estrategia es...", listOf("Forzar piezas", "Buscar las esquinas primero", "Tirar las piezas", "Pintarlas"), 1, "Programación básica"),
        Pregunta("Si un problema es muy difícil...", listOf("Lo divides en partes más fáciles", "Lo ignoras", "Lloras", "Lo borras"), 0, "Programación básica"),
        Pregunta("Un patrón es...", listOf("Algo que ocurre una vez", "Algo que se repite", "Un error", "Un jefe"), 1, "Programación básica"),
        Pregunta("¿Qué haces antes de programar?", listOf("Jugar", "Planear el algoritmo", "Dormir", "Comer"), 1, "Programación básica"),
        Pregunta("La 'prueba de escritorio' sirve para...", listOf("Limpiar la mesa", "Verificar el algoritmo manualmente", "Dibujar", "Escribir"), 1, "Programación básica"),
        Pregunta("Si tu código no funciona, tú...", listOf("Compras otra PC", "Revisas paso a paso (depuras)", "Gritas", "Lo dejas así"), 1, "Programación básica"),
        Pregunta("Una receta de cocina es un ejemplo de...", listOf("Hardware", "Algoritmo", "Variable", "Condicional"), 1, "Programación básica"),
        Pregunta("Identificar qué tienen en común un coche y un avión es...", listOf("Patrones", "Errores", "Bucles", "Datos"), 0, "Programación básica"),
        Pregunta("Al hacer un resumen, usas...", listOf("Repetición", "Abstracción (sacar lo importante)", "Suma", "Resta"), 1, "Programación básica"),
        Pregunta("El pensamiento computacional sirve para...", listOf("Solo computadoras", "Resolver problemas de la vida", "Solo matemáticas", "Solo videojuegos"), 1, "Programación básica"),
        Pregunta("Automatizar significa...", listOf("Hacerlo manual", "Que se haga solo o con máquina", "No hacerlo", "Hacerlo lento"), 1, "Programación básica"),
        Pregunta("¿Qué es un dato de entrada (Input)?", listOf("Lo que sale", "Lo que entra al sistema", "Un cable", "Un error"), 1, "Programación básica"),
        Pregunta("¿Qué es un dato de salida (Output)?", listOf("El resultado", "La información inicial", "El teclado", "El ratón"), 0, "Programación básica"),
        Pregunta("Para encontrar un libro en la biblioteca usas...", listOf("Suerte", "Un sistema de búsqueda (Algoritmo)", "Gritos", "Correr"), 1, "Programación básica"),
        Pregunta("La eficiencia en un algoritmo busca...", listOf("Hacerlo más lento", "Hacerlo en menos pasos/tiempo", "Hacerlo más difícil", "Usar más memoria"), 1, "Programación básica"),

        //Inglés
        Pregunta("¿Cómo se dice 'Rojo'?", listOf("Blue", "Red", "Green", "Yellow"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Perro'?", listOf("Cat", "Dog", "Bird", "Fish"), 1, "Inglés"),
        Pregunta("¿Qué significa 'Hello'?", listOf("Adiós", "Hola", "Gracias", "Por favor"), 1, "Inglés"),
        Pregunta("Traduce 'Book'", listOf("Mesa", "Libro", "Silla", "Lápiz"), 1, "Inglés"),
        Pregunta("Número 'One' es...", listOf("1", "2", "3", "10"), 0, "Inglés"),
        Pregunta("¿Cómo se dice 'Azul'?", listOf("Red", "Yellow", "Blue", "Black"), 2, "Inglés"),
        Pregunta("Traduce 'School'", listOf("Casa", "Escuela", "Parque", "Tienda"), 1, "Inglés"),
        Pregunta("¿Qué es 'Water'?", listOf("Fuego", "Aire", "Tierra", "Agua"), 3, "Inglés"),
        Pregunta("¿Cómo se dice 'Gato'?", listOf("Dog", "Cat", "Mouse", "Lion"), 1, "Inglés"),
        Pregunta("Traduce 'Family'", listOf("Amigos", "Familia", "Escuela", "Trabajo"), 1, "Inglés"),
        Pregunta("Significado de 'Thank you'", listOf("Hola", "De nada", "Gracias", "Perdón"), 2, "Inglés"),
        Pregunta("Color 'Yellow' es...", listOf("Rojo", "Verde", "Amarillo", "Azul"), 2, "Inglés"),
        Pregunta("Traduce 'House'", listOf("Casa", "Coche", "Perro", "Árbol"), 0, "Inglés"),
        Pregunta("El opuesto de 'Big' (Grande)", listOf("Tall", "Small", "Huge", "Fat"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Manzana'?", listOf("Banana", "Orange", "Apple", "Grape"), 2, "Inglés"),
        Pregunta("Número 'Ten' es...", listOf("5", "10", "20", "100"), 1, "Inglés"),
        Pregunta("Traduce 'Teacher'", listOf("Alumno", "Maestro", "Doctor", "Policía"), 1, "Inglés"),
        Pregunta("¿Qué es 'Sun'?", listOf("Luna", "Estrella", "Sol", "Nube"), 2, "Inglés"),
        Pregunta("¿Cómo se dice 'Amigo'?", listOf("Enemy", "Friend", "Brother", "Sister"), 1, "Inglés"),
        Pregunta("Traduce 'Good Morning'", listOf("Buenas Noches", "Buenos Días", "Hola", "Adiós"), 1, "Inglés"),
        Pregunta("Parte del cuerpo: 'Hand'", listOf("Pie", "Cabeza", "Mano", "Ojo"), 2, "Inglés"),
        Pregunta("Verbo: 'To Play'", listOf("Comer", "Dormir", "Jugar", "Correr"), 2, "Inglés"),
        Pregunta("Color 'Green' es...", listOf("Gris", "Verde", "Blanco", "Negro"), 1, "Inglés"),
        Pregunta("Traduce 'Father'", listOf("Madre", "Hermano", "Padre", "Tío"), 2, "Inglés"),
        Pregunta("Traduce 'Milk'", listOf("Agua", "Jugo", "Leche", "Refresco"), 2, "Inglés"),
        Pregunta("¿Cómo se dice 'Hermana'?", listOf("Brother", "Sister", "Mother", "Father"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Hermano'?", listOf("Sister", "Brother", "Uncle", "Aunt"), 1, "Inglés"),
        Pregunta("Color 'Black' es...", listOf("Blanco", "Negro", "Azul", "Rojo"), 1, "Inglés"),
        Pregunta("Color 'White' es...", listOf("Negro", "Blanco", "Gris", "Rosa"), 1, "Inglés"),
        Pregunta("Traduce 'Love'", listOf("Odio", "Amor", "Amigo", "Feliz"), 1, "Inglés"),
        Pregunta("Traduce 'Happy'", listOf("Triste", "Enojado", "Feliz", "Cansado"), 2, "Inglés"),
        Pregunta("Traduce 'Sad'", listOf("Feliz", "Triste", "Rápido", "Lento"), 1, "Inglés"),
        Pregunta("Número 'Two' es...", listOf("1", "2", "3", "4"), 1, "Inglés"),
        Pregunta("Número 'Three' es...", listOf("2", "3", "4", "5"), 1, "Inglés"),
        Pregunta("Número 'Five' es...", listOf("4", "5", "6", "7"), 1, "Inglés"),
        Pregunta("¿Qué es 'Moon'?", listOf("Sol", "Estrella", "Luna", "Cielo"), 2, "Inglés"),
        Pregunta("¿Qué es 'Star'?", listOf("Estrella", "Luna", "Sol", "Planeta"), 0, "Inglés"),
        Pregunta("¿Qué es 'Sky'?", listOf("Mar", "Tierra", "Cielo", "Fuego"), 2, "Inglés"),
        Pregunta("Traduce 'Boy'", listOf("Niña", "Niño", "Hombre", "Mujer"), 1, "Inglés"),
        Pregunta("Traduce 'Girl'", listOf("Niño", "Niña", "Señora", "Bebé"), 1, "Inglés"),
        Pregunta("Animal 'Lion' es...", listOf("Tigre", "León", "Gato", "Perro"), 1, "Inglés"),
        Pregunta("Animal 'Fish' es...", listOf("Pez", "Pájaro", "Rana", "Tortuga"), 0, "Inglés"),
        Pregunta("Verbo 'To Run'", listOf("Caminar", "Correr", "Saltar", "Dormir"), 1, "Inglés"),
        Pregunta("Verbo 'To Eat'", listOf("Beber", "Comer", "Cocinar", "Hablar"), 1, "Inglés"),
        Pregunta("Verbo 'To Sleep'", listOf("Despertar", "Dormir", "Soñar", "Acostar"), 1, "Inglés"),
        Pregunta("Parte del cuerpo: 'Head'", listOf("Mano", "Pie", "Cabeza", "Brazo"), 2, "Inglés"),
        Pregunta("Parte del cuerpo: 'Eye'", listOf("Ojo", "Nariz", "Boca", "Oreja"), 0, "Inglés"),
        Pregunta("Parte del cuerpo: 'Mouth'", listOf("Nariz", "Ojo", "Boca", "Diente"), 2, "Inglés"),
        Pregunta("Día 'Monday' es...", listOf("Martes", "Lunes", "Domingo", "Viernes"), 1, "Inglés"),
        Pregunta("Día 'Sunday' es...", listOf("Sábado", "Domingo", "Lunes", "Jueves"), 1, "Inglés"),
        Pregunta("Día 'Friday' es...", listOf("Jueves", "Viernes", "Sábado", "Lunes"), 1, "Inglés"),
        Pregunta("Mes 'January' es...", listOf("Febrero", "Enero", "Junio", "Julio"), 1, "Inglés"),
        Pregunta("Mes 'December' es...", listOf("Noviembre", "Diciembre", "Enero", "Octubre"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Frío'?", listOf("Hot", "Cold", "Warm", "Cool"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Calor'?", listOf("Cold", "Hot", "Ice", "Fire"), 1, "Inglés"),
        Pregunta("Traduce 'Car'", listOf("Avión", "Coche", "Bici", "Tren"), 1, "Inglés"),
        Pregunta("Traduce 'Bike'", listOf("Coche", "Bicicleta", "Moto", "Patines"), 1, "Inglés"),
        Pregunta("Objeto 'Pen' es...", listOf("Lápiz", "Pluma/Bolígrafo", "Goma", "Regla"), 1, "Inglés"),
        Pregunta("Objeto 'Pencil' es...", listOf("Pluma", "Lápiz", "Color", "Marcador"), 1, "Inglés"),
        Pregunta("Lugar 'City' es...", listOf("Campo", "Ciudad", "Pueblo", "Playa"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Adios'?", listOf("Hello", "Goodbye", "Please", "Thanks"), 1, "Inglés"),
        Pregunta("¿Cómo se dice 'Por favor'?", listOf("Thanks", "Please", "Sorry", "Excuse me"), 1, "Inglés"),
        Pregunta("Color 'Pink' es...", listOf("Morado", "Rosa", "Naranja", "Rojo"), 1, "Inglés"),
        Pregunta("Color 'Orange' es...", listOf("Rojo", "Naranja", "Amarillo", "Café"), 1, "Inglés"),
        Pregunta("Color 'Purple' es...", listOf("Rosa", "Morado", "Azul", "Negro"), 1, "Inglés"),

    )

    fun obtenerPreguntaAleatoria(): Pregunta {
        return preguntas.random()
    }
}