package com.proyectofinal.brainchis

import kotlin.random.Random

object BancoPreguntas {

    private val preguntas = listOf(
        //Matemáticas
        Pregunta("¿Cuánto es 5 + 5?", listOf("8", "10", "12", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 8 x 5?", listOf("40", "35", "45", "30"), 0, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un triángulo?", listOf("3", "4", "5", "6"), 0, "Matemáticas"),
        Pregunta("¿Cuál es la mitad de 50?", listOf("20", "25", "30", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 100 - 30?", listOf("60", "80", "70", "50"), 2, "Matemáticas"),
        Pregunta("¿Qué figura es redonda?", listOf("Cuadrado", "Círculo", "Triángulo", "Rombo"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 12 / 4?", listOf("2", "4", "3", "6"), 2, "Matemáticas"),
        Pregunta("¿Cuántos minutos tiene una hora?", listOf("100", "50", "30", "60"), 3, "Matemáticas"),
        Pregunta("El doble de 8 es...", listOf("16", "18", "14", "20"), 0, "Matemáticas"),
        Pregunta("¿Cuánto es 7 x 7?", listOf("49", "42", "56", "47"), 0, "Matemáticas"),
        Pregunta("¿Qué número es impar?", listOf("2", "4", "8", "7"), 3, "Matemáticas"),
        Pregunta("¿Qué número es par?", listOf("3", "5", "6", "9"), 2, "Matemáticas"),
        Pregunta("Una docena son...", listOf("10", "12", "20", "6"), 1, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un cuadrado?", listOf("4", "5", "3", "6"), 0, "Matemáticas"),
        Pregunta("Suma: 15 + 15", listOf("20", "25", "30", "35"), 2, "Matemáticas"),
        Pregunta("Resta: 20 - 8", listOf("10", "11", "13", "12"), 3, "Matemáticas"),
        Pregunta("¿Cuánto es 9 x 2?", listOf("18", "20", "16", "19"), 0, "Matemáticas"),
        Pregunta("Si tienes 3 manzanas y comes 1, quedan...", listOf("1", "3", "2", "0"), 2, "Matemáticas"),
        Pregunta("¿Cuál es mayor?", listOf("10", "50", "9", "49"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 10 x 10?", listOf("100", "1000", "20", "50"), 0, "Matemáticas"),
        Pregunta("¿Cuántas horas tiene un día?", listOf("12", "20", "24", "48"), 2, "Matemáticas"),
        Pregunta("La figura de 5 lados se llama...", listOf("Cuadrado", "Hexágono", "Pentágono", "Triángulo"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 6 x 3?", listOf("12", "18", "24", "16"), 1, "Matemáticas"),
        Pregunta("Suma: 50 + 50", listOf("90", "100", "110", "120"), 1, "Matemáticas"),
        Pregunta("¿Cuál es el número romano V?", listOf("1", "10", "5", "100"), 2, "Matemáticas"),
        //--- MATEMÁTICAS (BLOQUE 2) ---
        Pregunta("¿Cuánto es 20 + 20?", listOf("30", "40", "50", "60"), 1, "Matemáticas"),
        Pregunta("¿Cuántos lados tiene un rectángulo?", listOf("3", "4", "5", "6"), 1, "Matemáticas"),
        Pregunta("El doble de 10 es...", listOf("15", "20", "30", "100"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 3 x 3?", listOf("6", "9", "12", "33"), 1, "Matemáticas"),
        Pregunta("La mitad de 10 es...", listOf("2", "5", "4", "6"), 1, "Matemáticas"),
        Pregunta("¿Qué número sigue? 2, 4, 6, ...", listOf("7", "8", "9", "10"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 15 - 5?", listOf("5", "15", "10", "20"), 2, "Matemáticas"),
        Pregunta("Un metro tiene 100...", listOf("Metros", "Kilómetros", "Centímetros", "Litros"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 5 x 4?", listOf("15", "20", "25", "10"), 1, "Matemáticas"),
        Pregunta("¿Qué figura tiene 3 lados?", listOf("Cuadrado", "Círculo", "Triángulo", "Rombo"), 2, "Matemáticas"),
        Pregunta("Suma: 100 + 200", listOf("200", "300", "400", "500"), 1, "Matemáticas"),
        Pregunta("Resta: 50 - 25", listOf("25", "30", "15", "20"), 0, "Matemáticas"),
        Pregunta("¿Cuánto es 6 x 2?", listOf("10", "12", "14", "8"), 1, "Matemáticas"),
        Pregunta("¿Qué mide un reloj?", listOf("Peso", "Altura", "Tiempo", "Distancia"), 2, "Matemáticas"),
        Pregunta("¿Qué número es mayor?", listOf("100", "99", "101", "90"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 8 / 2?", listOf("2", "3", "4", "5"), 2, "Matemáticas"),
        Pregunta("La tercia de 9 es...", listOf("2", "3", "4", "6"), 1, "Matemáticas"),
        Pregunta("¿Cuántos días tiene una semana?", listOf("5", "6", "7", "8"), 2, "Matemáticas"),
        Pregunta("¿Cuántos meses tiene un año?", listOf("10", "11", "12", "14"), 2, "Matemáticas"),
        Pregunta("¿Qué número es menor?", listOf("5", "8", "2", "10"), 2, "Matemáticas"),
        Pregunta("Suma: 8 + 7", listOf("14", "15", "16", "13"), 1, "Matemáticas"),
        Pregunta("El triple de 3 es...", listOf("6", "9", "12", "3"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 10 - 7?", listOf("2", "3", "4", "1"), 1, "Matemáticas"),
        Pregunta("¿Qué usas para medir tu altura?", listOf("Báscula", "Metro", "Reloj", "Termómetro"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 4 x 4?", listOf("12", "14", "16", "20"), 2, "Matemáticas"),
        Pregunta("Figura que parece una pelota", listOf("Cubo", "Esfera", "Pirámide", "Cono"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 11 + 11?", listOf("20", "21", "22", "23"), 2, "Matemáticas"),
        Pregunta("Resta: 30 - 10", listOf("10", "20", "30", "15"), 1, "Matemáticas"),
        Pregunta("¿Cuánto es 2 x 9?", listOf("16", "17", "18", "20"), 2, "Matemáticas"),
        Pregunta("¿Cuántos segundos tiene un minuto?", listOf("30", "45", "60", "100"), 2, "Matemáticas"),
        Pregunta("Suma: 6 + 6", listOf("10", "11", "12", "13"), 2, "Matemáticas"),
        Pregunta("¿Cuál es número par?", listOf("1", "3", "5", "8"), 3, "Matemáticas"),
        Pregunta("¿Cuál es número impar?", listOf("2", "4", "6", "9"), 3, "Matemáticas"),
        Pregunta("¿Cuánto es 40 + 10?", listOf("40", "50", "60", "30"), 1, "Matemáticas"),
        Pregunta("La mitad de 100 es...", listOf("40", "60", "50", "25"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 5 x 5?", listOf("20", "30", "35", "25"), 3, "Matemáticas"),
        Pregunta("¿Cuántas caras tiene un cubo?", listOf("4", "5", "6", "8"), 2, "Matemáticas"),
        Pregunta("Suma: 9 + 9", listOf("16", "17", "18", "19"), 2, "Matemáticas"),
        Pregunta("¿Cuánto es 20 / 2?", listOf("5", "10", "15", "2"), 1, "Matemáticas"),
        Pregunta("El número anterior a 20 es...", listOf("18", "21", "19", "22"), 2, "Matemáticas"),

        //Ciencias
        Pregunta("¿Cuál es el planeta rojo?", listOf("Tierra", "Marte", "Júpiter", "Venus"), 1, "Ciencias"),
        Pregunta("¿Qué respiran los humanos?", listOf("Oxígeno", "Helio", "Agua", "Carbón"), 0, "Ciencias"),
        Pregunta("¿El animal más grande del mundo?", listOf("Elefante", "Ballena Azul", "Tiburón", "Jirafa"), 1, "Ciencias"),
        Pregunta("¿Cuántas patas tiene una araña?", listOf("6", "4", "8", "10"), 2, "Ciencias"),
        Pregunta("El Sol es una...", listOf("Estrella", "Planeta", "Luna", "Cometa"), 0, "Ciencias"),
        Pregunta("¿Qué animal produce leche?", listOf("Vaca", "Gallina", "Pez", "Tortuga"), 0, "Ciencias"),
        Pregunta("¿Qué comen los herbívoros?", listOf("Carne", "Plantas", "Insectos", "Todo"), 1, "Ciencias"),
        Pregunta("¿Estado del hielo?", listOf("Líquido", "Sólido", "Gaseoso", "Plasma"), 1, "Ciencias"),
        Pregunta("¿Cuántos huesos tiene un adulto (aprox)?", listOf("100", "500", "206", "300"), 2, "Ciencias"),
        Pregunta("Órgano que bombea sangre", listOf("Pulmón", "Cerebro", "Corazón", "Estómago"), 2, "Ciencias"),
        Pregunta("¿Qué nos da luz natural?", listOf("Luna", "Sol", "Fuego", "Bombilla"), 1, "Ciencias"),
        Pregunta("Animal que vuela", listOf("Perro", "Gato", "Águila", "Elefante"), 2, "Ciencias"),
        Pregunta("Líquido vital para la vida", listOf("Refresco", "Aceite", "Agua", "Leche"), 2, "Ciencias"),
        Pregunta("El satélite de la Tierra es...", listOf("Sol", "Luna", "Marte", "Júpiter"), 1, "Ciencias"),
        Pregunta("Animal rey de la selva", listOf("Tigre", "León", "Mono", "Oso"), 1, "Ciencias"),
        Pregunta("¿Qué parte de la planta está bajo tierra?", listOf("Hoja", "Tallo", "Raíz", "Flor"), 2, "Ciencias"),
        Pregunta("Animal que vive en el agua", listOf("Pájaro", "Pez", "León", "Gato"), 1, "Ciencias"),
        Pregunta("¿Dónde digerimos la comida?", listOf("Estómago", "Corazón", "Pulmones", "Cerebro"), 0, "Ciencias"),
        Pregunta("Planeta con anillos", listOf("Marte", "Saturno", "Venus", "Mercurio"), 1, "Ciencias"),
        Pregunta("¿Qué animal pone huevos?", listOf("Perro", "Gato", "Gallina", "Vaca"), 2, "Ciencias"),
        Pregunta("La fórmula H2O es...", listOf("Sal", "Aire", "Oro", "Agua"), 3, "Ciencias"),
        Pregunta("¿Qué usamos para pensar?", listOf("Corazón", "Cerebro", "Hígado", "Riñón"), 1, "Ciencias"),
        Pregunta("El agua hierve a...", listOf("50°C", "80°C", "100°C", "200°C"), 2, "Ciencias"),
        Pregunta("¿Cuántos dientes de leche tenemos?", listOf("20", "32", "10", "50"), 0, "Ciencias"),
        Pregunta("Gas que exhalamos", listOf("Oxígeno", "Dióxido de Carbono", "Helio", "Nitrógeno"), 1, "Ciencias"),
        Pregunta("Animal que tiene trompa", listOf("Elefante", "Jirafa", "León", "Oso"), 0, "Ciencias"),
        Pregunta("¿Qué nos da calor?", listOf("Hielo", "Fuego", "Agua", "Viento"), 1, "Ciencias"),
        Pregunta("¿De dónde viene la lluvia?", listOf("Suelo", "Nubes", "Sol", "Luna"), 1, "Ciencias"),
        Pregunta("Animal que ladra", listOf("Gato", "Vaca", "Perro", "Pato"), 2, "Ciencias"),
        Pregunta("¿Qué parte del cuerpo usamos para ver?", listOf("Oídos", "Nariz", "Ojos", "Boca"), 2, "Ciencias"),
        Pregunta("¿Qué parte del cuerpo usamos para oír?", listOf("Ojos", "Oídos", "Manos", "Pies"), 1, "Ciencias"),
        Pregunta("El hielo es agua en estado...", listOf("Líquido", "Sólido", "Gaseoso", "Vapor"), 1, "Ciencias"),
        Pregunta("Animal que maúlla", listOf("Perro", "Pájaro", "Gato", "Ratón"), 2, "Ciencias"),
        Pregunta("¿Qué respiran los peces?", listOf("Aire", "Oxígeno del agua", "Tierra", "Fuego"), 1, "Ciencias"),
        Pregunta("¿Cuántas estaciones tiene el año?", listOf("2", "3", "4", "5"), 2, "Ciencias"),
        Pregunta("Estación donde hace frío", listOf("Verano", "Primavera", "Otoño", "Invierno"), 3, "Ciencias"),
        Pregunta("Estación donde hace calor", listOf("Invierno", "Otoño", "Verano", "Primavera"), 2, "Ciencias"),
        Pregunta("Fruta amarilla y curva", listOf("Manzana", "Plátano", "Uva", "Naranja"), 1, "Ciencias"),
        Pregunta("¿Qué sale de un volcán?", listOf("Agua", "Lava", "Hielo", "Flores"), 1, "Ciencias"),
        Pregunta("Animal que tiene cuello muy largo", listOf("Elefante", "Jirafa", "Caballo", "Tigre"), 1, "Ciencias"),
        Pregunta("¿Qué necesitan las plantas para vivir?", listOf("Coca-Cola", "Agua y Sol", "Oscuridad", "Jugo"), 1, "Ciencias"),
        Pregunta("El Sol sale por el...", listOf("Norte", "Sur", "Este", "Oeste"), 2, "Ciencias"),
        Pregunta("¿Qué cubre el cuerpo de las aves?", listOf("Pelo", "Escamas", "Plumas", "Piel"), 2, "Ciencias"),
        Pregunta("¿Qué cubre el cuerpo de los peces?", listOf("Pelo", "Escamas", "Plumas", "Ropa"), 1, "Ciencias"),
        Pregunta("Animal que da lana", listOf("Vaca", "Cerdo", "Oveja", "Caballo"), 2, "Ciencias"),
        Pregunta("¿Cuál es un ser vivo?", listOf("Piedra", "Árbol", "Mesa", "Coche"), 1, "Ciencias"),
        Pregunta("¿Cuál NO es un ser vivo?", listOf("Gato", "Planta", "Niño", "Juguete"), 3, "Ciencias"),
        Pregunta("¿Qué usamos para oler?", listOf("Boca", "Ojos", "Nariz", "Orejas"), 2, "Ciencias"),
        Pregunta("¿Qué usamos para saborear?", listOf("Lengua", "Dientes", "Labios", "Nariz"), 0, "Ciencias"),
        Pregunta("Animal que salta y es verde", listOf("Perro", "Rana", "Gato", "Vaca"), 1, "Ciencias"),
        Pregunta("¿Qué comen las vacas?", listOf("Carne", "Pasto", "Peces", "Insectos"), 1, "Ciencias"),
        Pregunta("Líquido blanco que bebemos", listOf("Agua", "Jugo", "Leche", "Aceite"), 2, "Ciencias"),
        Pregunta("¿Dónde viven los osos polares?", listOf("Desierto", "Selva", "Polo Norte", "Playa"), 2, "Ciencias"),
        Pregunta("El órgano que controla el cuerpo es...", listOf("Corazón", "Cerebro", "Estómago", "Hueso"), 1, "Ciencias"),
        Pregunta("¿Cuántas patas tiene un perro?", listOf("2", "4", "6", "8"), 1, "Ciencias"),
        Pregunta("Animal que vuela de noche", listOf("Águila", "Murciélago", "Pato", "Gallina"), 1, "Ciencias"),
        Pregunta("¿Qué es la Tierra?", listOf("Una estrella", "Un planeta", "Una luna", "Un cometa"), 1, "Ciencias"),
        Pregunta("¿De qué color es la sangre?", listOf("Azul", "Verde", "Roja", "Amarilla"), 2, "Ciencias"),
        Pregunta("¿Qué insecto hace miel?", listOf("Mosca", "Abeja", "Hormiga", "Mariposa"), 1, "Ciencias"),
        Pregunta("Animal más alto del mundo", listOf("Elefante", "Jirafa", "Oso", "León"), 1, "Ciencias"),
        Pregunta("¿Qué animal es 'Rey de la Selva'?", listOf("Tigre", "León", "Lobo", "Zorro"), 1, "Ciencias"),
        Pregunta("¿Qué protege nuestro cerebro?", listOf("Costillas", "Cráneo", "Piel", "Pelo"), 1, "Ciencias"),
        Pregunta("¿Qué usamos para caminar?", listOf("Manos", "Brazos", "Piernas", "Cabeza"), 2, "Ciencias"),
        Pregunta("La luna sale de...", listOf("Día", "Noche", "Tarde", "Mañana"), 1, "Ciencias"),
        Pregunta("¿Qué es un renacuajo?", listOf("Un pez", "Una rana bebé", "Un insecto", "Un pájaro"), 1, "Ciencias"),

        //Tecnología
        Pregunta("¿Qué usas para escribir en la PC?", listOf("Ratón", "Teclado", "Pantalla", "Cable"), 1, "Tecnología"),
        Pregunta("El 'cerebro' de la computadora es...", listOf("Mouse", "Teclado", "CPU", "USB"), 2, "Tecnología"),
        Pregunta("¿Qué usas para hacer clic?", listOf("Teclado", "Ratón (Mouse)", "Pantalla", "Altavoz"), 1, "Tecnología"),
        Pregunta("¿Dónde ves la imagen de la PC?", listOf("Teclado", "Monitor", "CPU", "Impresora"), 1, "Tecnología"),
        Pregunta("¿Qué significa 'PC'?", listOf("Personal Computer", "Para Comer", "Poco Calor", "Pantalla Chica"), 0, "Tecnología"),
        Pregunta("Sirve para buscar en internet", listOf("Word", "Excel", "Google", "Paint"), 2, "Tecnología"),
        Pregunta("Sistema operativo de móviles", listOf("Windows", "Android", "Mac", "Linux"), 1, "Tecnología"),
        Pregunta("Un error en un programa se llama...", listOf("Bicho", "Bug", "Virus", "Hacker"), 1, "Tecnología"),
        Pregunta("Sirve para guardar archivos", listOf("Pantalla", "Disco Duro", "Ratón", "Teclado"), 1, "Tecnología"),
        Pregunta("Red mundial de computadoras", listOf("Intranet", "Internet", "Ethernet", "Extranet"), 1, "Tecnología"),
        Pregunta("Programa para navegar", listOf("Chrome", "Word", "Excel", "PowerPoint"), 0, "Tecnología"),
        Pregunta("¿Qué es el Wi-Fi?", listOf("Comida", "Internet sin cables", "Un virus", "Un juego"), 1, "Tecnología"),
        Pregunta("Sirve para imprimir en papel", listOf("Escáner", "Impresora", "Cámara", "Bocina"), 1, "Tecnología"),
        Pregunta("¿Qué es un 'App'?", listOf("Un animal", "Una aplicación", "Un aparato", "Un amigo"), 1, "Tecnología"),
        Pregunta("Lenguaje de programación", listOf("Snake", "Python", "Lizard", "Turtle"), 1, "Tecnología"),
        Pregunta("Dispositivo portátil de Apple", listOf("Galaxy", "iPhone", "Pixel", "Nokia"), 1, "Tecnología"),
        Pregunta("¿Qué hace el comando 'Ctrl + C'?", listOf("Pegar", "Copiar", "Cortar", "Borrar"), 1, "Tecnología"),
        Pregunta("¿Qué hace el comando 'Ctrl + V'?", listOf("Pegar", "Copiar", "Cortar", "Borrar"), 0, "Tecnología"),
        Pregunta("Plataforma de videos", listOf("Facebook", "YouTube", "WhatsApp", "Gmail"), 1, "Tecnología"),
        Pregunta("Correo electrónico", listOf("e-Letter", "e-Mail", "e-Box", "e-Post"), 1, "Tecnología"),
        Pregunta("¿Qué protege tu cuenta?", listOf("Usuario", "Contraseña", "Nombre", "Foto"), 1, "Tecnología"),
        Pregunta("Parte física de la computadora", listOf("Software", "Hardware", "Freeware", "Malware"), 1, "Tecnología"),
        Pregunta("Programas y aplicaciones", listOf("Software", "Hardware", "Hard-disk", "Screen"), 0, "Tecnología"),
        Pregunta("Red social de fotos", listOf("Excel", "Instagram", "Word", "Outlook"), 1, "Tecnología"),
        Pregunta("Dispositivo para videojuegos", listOf("Consola", "Microondas", "Radio", "Calculadora"), 0, "Tecnología"),
        Pregunta("¿Qué usamos para escuchar música en privado?", listOf("Bocinas", "Audífonos", "Micrófono", "Pantalla"), 1, "Tecnología"),
        Pregunta("Aparato para cambiar de canal la TV", listOf("Ratón", "Control Remoto", "Teclado", "Celular"), 1, "Tecnología"),
        Pregunta("¿Qué es Google?", listOf("Un juego", "Un buscador", "Una red social", "Un antivirus"), 1, "Tecnología"),
        Pregunta("Plataforma para ver videos", listOf("Spotify", "YouTube", "Excel", "Word"), 1, "Tecnología"),
        Pregunta("¿Qué necesitas para usar internet?", listOf("Agua", "Luz", "Wi-Fi o Datos", "Gas"), 2, "Tecnología"),
        Pregunta("¿Qué carga la batería del celular?", listOf("Audífonos", "Cargador", "Funda", "Protector"), 1, "Tecnología"),
        Pregunta("Sirve para tomar fotos", listOf("Impresora", "Cámara", "Bocina", "Teclado"), 1, "Tecnología"),
        Pregunta("¿Qué tecla borra letras?", listOf("Enter", "Espacio", "Borrar (Backspace)", "Shift"), 2, "Tecnología"),
        Pregunta("Tecla para hacer espacio", listOf("Enter", "Espaciadora", "Escape", "Control"), 1, "Tecnología"),
        Pregunta("¿Qué es 'Facebook'?", listOf("Un libro", "Una red social", "Un juego", "Un buscador"), 1, "Tecnología"),
        Pregunta("Aparato para hablar a distancia", listOf("Calculadora", "Teléfono", "Reloj", "Brújula"), 1, "Tecnología"),
        Pregunta("¿Qué es un 'Tablet'?", listOf("Una pastilla", "Una computadora táctil", "Una mesa", "Un teléfono viejo"), 1, "Tecnología"),
        Pregunta("Juego de bloques muy famoso", listOf("Mario", "Minecraft", "Sonic", "Zelda"), 1, "Tecnología"),
        Pregunta("¿Qué usas para escribir un correo?", listOf("Papel", "Lápiz", "Computadora/Celular", "Tijeras"), 2, "Tecnología"),
        Pregunta("¿Qué es un 'Gamer'?", listOf("Alguien que cocina", "Alguien que juega videojuegos", "Alguien que lee", "Alguien que corre"), 1, "Tecnología"),
        Pregunta("Dispositivo para mover el cursor", listOf("Teclado", "Ratón (Mouse)", "Impresora", "Monitor"), 1, "Tecnología"),
        Pregunta("¿Qué significa 'WWW'?", listOf("World Wide Web", "World Wild West", "Web World Wide", "Wide Web World"), 0, "Tecnología"),
        Pregunta("¿Qué es un 'Password'?", listOf("Un pasaporte", "Una contraseña", "Una palabra", "Un pase"), 1, "Tecnología"),
        Pregunta("Icono de 'Guardar' suele ser...", listOf("Un disquete", "Una carpeta", "Un lápiz", "Una basura"), 0, "Tecnología"),
        Pregunta("Icono de 'Papelera' es para...", listOf("Guardar", "Borrar", "Copiar", "Pegar"), 1, "Tecnología"),
        Pregunta("¿Qué es 'WhatsApp'?", listOf("Para ver videos", "Para mensajería", "Para música", "Para dibujar"), 1, "Tecnología"),
        Pregunta("¿Qué es el 'Hardware'?", listOf("Lo que se toca", "Los programas", "Internet", "El Wi-Fi"), 0, "Tecnología"),
        Pregunta("¿Qué es el 'Software'?", listOf("El teclado", "La pantalla", "Los programas", "El ratón"), 2, "Tecnología"),
        Pregunta("Sistema operativo de iPhone", listOf("Android", "iOS", "Windows", "Linux"), 1, "Tecnología"),
        Pregunta("Buscador más famoso", listOf("Bing", "Yahoo", "Google", "Ask"), 2, "Tecnología"),
        Pregunta("¿Qué es un 'Like'?", listOf("Un odio", "Un me gusta", "Un compartir", "Un comentario"), 1, "Tecnología"),
        Pregunta("¿Qué usas para videollamadas?", listOf("Calculadora", "Cámara Web (Webcam)", "Impresora", "Scanner"), 1, "Tecnología"),
        Pregunta("Sirve para escribir en papel desde la PC", listOf("Ratón", "Impresora", "Monitor", "Teclado"), 1, "Tecnología"),
        Pregunta("¿Qué es un 'Virus' informático?", listOf("Algo bueno", "Algo dañino", "Un juego", "Una foto"), 1, "Tecnología"),
        Pregunta("Para encender la PC presionas...", listOf("Enter", "Botón de encendido", "Espacio", "Click"), 1, "Tecnología"),
        Pregunta("¿Qué es 'Netflix'?", listOf("Para ver películas", "Para escuchar música", "Para escribir", "Para jugar"), 0, "Tecnología"),
        Pregunta("¿Qué es 'Spotify'?", listOf("Para ver películas", "Para escuchar música", "Para fotos", "Para mapas"), 1, "Tecnología"),
        Pregunta("Dispositivo que almacena mucha información", listOf("Disco Duro", "Memoria RAM", "Procesador", "Ventilador"), 0, "Tecnología"),
        Pregunta("¿Qué es un 'Pixel'?", listOf("Un punto en la pantalla", "Un cable", "Un botón", "Un sonido"), 0, "Tecnología"),
        Pregunta("Marca de la manzanita", listOf("Samsung", "Apple", "Sony", "LG"), 1, "Tecnología"),
        Pregunta("¿Qué es 'Zoom'?", listOf("Para correr", "Para videollamadas", "Para comer", "Para dormir"), 1, "Tecnología"),
        Pregunta("La 'Nube' sirve para...", listOf("Llover", "Guardar datos en internet", "Volar", "Dar sombra"), 1, "Tecnología"),
        Pregunta("¿Qué es un 'Emoji'?", listOf("Una letra", "Una carita/dibujo", "Un número", "Un virus"), 1, "Tecnología"),
        Pregunta("El cerebro de la computadora es...", listOf("Monitor", "Teclado", "Procesador (CPU)", "Mouse"), 2, "Tecnología"),
        Pregunta("¿Qué cable conecta a la TV?", listOf("HDMI", "USB", "Aux", "VGA"), 0, "Tecnología"),

        //Idiomas (Inglés)
        Pregunta("¿Cómo se dice 'Rojo'?", listOf("Blue", "Red", "Green", "Yellow"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Perro'?", listOf("Cat", "Dog", "Bird", "Fish"), 1, "Idiomas"),
        Pregunta("¿Qué significa 'Hello'?", listOf("Adiós", "Hola", "Gracias", "Por favor"), 1, "Idiomas"),
        Pregunta("Traduce 'Book'", listOf("Mesa", "Libro", "Silla", "Lápiz"), 1, "Idiomas"),
        Pregunta("Número 'One' es...", listOf("1", "2", "3", "10"), 0, "Idiomas"),
        Pregunta("¿Cómo se dice 'Azul'?", listOf("Red", "Yellow", "Blue", "Black"), 2, "Idiomas"),
        Pregunta("Traduce 'School'", listOf("Casa", "Escuela", "Parque", "Tienda"), 1, "Idiomas"),
        Pregunta("¿Qué es 'Water'?", listOf("Fuego", "Aire", "Tierra", "Agua"), 3, "Idiomas"),
        Pregunta("¿Cómo se dice 'Gato'?", listOf("Dog", "Cat", "Mouse", "Lion"), 1, "Idiomas"),
        Pregunta("Traduce 'Family'", listOf("Amigos", "Familia", "Escuela", "Trabajo"), 1, "Idiomas"),
        Pregunta("Significado de 'Thank you'", listOf("Hola", "De nada", "Gracias", "Perdón"), 2, "Idiomas"),
        Pregunta("Color 'Yellow' es...", listOf("Rojo", "Verde", "Amarillo", "Azul"), 2, "Idiomas"),
        Pregunta("Traduce 'House'", listOf("Casa", "Coche", "Perro", "Árbol"), 0, "Idiomas"),
        Pregunta("El opuesto de 'Big' (Grande)", listOf("Tall", "Small", "Huge", "Fat"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Manzana'?", listOf("Banana", "Orange", "Apple", "Grape"), 2, "Idiomas"),
        Pregunta("Número 'Ten' es...", listOf("5", "10", "20", "100"), 1, "Idiomas"),
        Pregunta("Traduce 'Teacher'", listOf("Alumno", "Maestro", "Doctor", "Policía"), 1, "Idiomas"),
        Pregunta("¿Qué es 'Sun'?", listOf("Luna", "Estrella", "Sol", "Nube"), 2, "Idiomas"),
        Pregunta("¿Cómo se dice 'Amigo'?", listOf("Enemy", "Friend", "Brother", "Sister"), 1, "Idiomas"),
        Pregunta("Traduce 'Good Morning'", listOf("Buenas Noches", "Buenos Días", "Hola", "Adiós"), 1, "Idiomas"),
        Pregunta("Parte del cuerpo: 'Hand'", listOf("Pie", "Cabeza", "Mano", "Ojo"), 2, "Idiomas"),
        Pregunta("Verbo: 'To Play'", listOf("Comer", "Dormir", "Jugar", "Correr"), 2, "Idiomas"),
        Pregunta("Color 'Green' es...", listOf("Gris", "Verde", "Blanco", "Negro"), 1, "Idiomas"),
        Pregunta("Traduce 'Father'", listOf("Madre", "Hermano", "Padre", "Tío"), 2, "Idiomas"),
        Pregunta("Traduce 'Milk'", listOf("Agua", "Jugo", "Leche", "Refresco"), 2, "Idiomas"),
        Pregunta("¿Cómo se dice 'Hermana'?", listOf("Brother", "Sister", "Mother", "Father"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Hermano'?", listOf("Sister", "Brother", "Uncle", "Aunt"), 1, "Idiomas"),
        Pregunta("Color 'Black' es...", listOf("Blanco", "Negro", "Azul", "Rojo"), 1, "Idiomas"),
        Pregunta("Color 'White' es...", listOf("Negro", "Blanco", "Gris", "Rosa"), 1, "Idiomas"),
        Pregunta("Traduce 'Love'", listOf("Odio", "Amor", "Amigo", "Feliz"), 1, "Idiomas"),
        Pregunta("Traduce 'Happy'", listOf("Triste", "Enojado", "Feliz", "Cansado"), 2, "Idiomas"),
        Pregunta("Traduce 'Sad'", listOf("Feliz", "Triste", "Rápido", "Lento"), 1, "Idiomas"),
        Pregunta("Número 'Two' es...", listOf("1", "2", "3", "4"), 1, "Idiomas"),
        Pregunta("Número 'Three' es...", listOf("2", "3", "4", "5"), 1, "Idiomas"),
        Pregunta("Número 'Five' es...", listOf("4", "5", "6", "7"), 1, "Idiomas"),
        Pregunta("¿Qué es 'Moon'?", listOf("Sol", "Estrella", "Luna", "Cielo"), 2, "Idiomas"),
        Pregunta("¿Qué es 'Star'?", listOf("Estrella", "Luna", "Sol", "Planeta"), 0, "Idiomas"),
        Pregunta("¿Qué es 'Sky'?", listOf("Mar", "Tierra", "Cielo", "Fuego"), 2, "Idiomas"),
        Pregunta("Traduce 'Boy'", listOf("Niña", "Niño", "Hombre", "Mujer"), 1, "Idiomas"),
        Pregunta("Traduce 'Girl'", listOf("Niño", "Niña", "Señora", "Bebé"), 1, "Idiomas"),
        Pregunta("Animal 'Lion' es...", listOf("Tigre", "León", "Gato", "Perro"), 1, "Idiomas"),
        Pregunta("Animal 'Fish' es...", listOf("Pez", "Pájaro", "Rana", "Tortuga"), 0, "Idiomas"),
        Pregunta("Verbo 'To Run'", listOf("Caminar", "Correr", "Saltar", "Dormir"), 1, "Idiomas"),
        Pregunta("Verbo 'To Eat'", listOf("Beber", "Comer", "Cocinar", "Hablar"), 1, "Idiomas"),
        Pregunta("Verbo 'To Sleep'", listOf("Despertar", "Dormir", "Soñar", "Acostar"), 1, "Idiomas"),
        Pregunta("Parte del cuerpo: 'Head'", listOf("Mano", "Pie", "Cabeza", "Brazo"), 2, "Idiomas"),
        Pregunta("Parte del cuerpo: 'Eye'", listOf("Ojo", "Nariz", "Boca", "Oreja"), 0, "Idiomas"),
        Pregunta("Parte del cuerpo: 'Mouth'", listOf("Nariz", "Ojo", "Boca", "Diente"), 2, "Idiomas"),
        Pregunta("Día 'Monday' es...", listOf("Martes", "Lunes", "Domingo", "Viernes"), 1, "Idiomas"),
        Pregunta("Día 'Sunday' es...", listOf("Sábado", "Domingo", "Lunes", "Jueves"), 1, "Idiomas"),
        Pregunta("Día 'Friday' es...", listOf("Jueves", "Viernes", "Sábado", "Lunes"), 1, "Idiomas"),
        Pregunta("Mes 'January' es...", listOf("Febrero", "Enero", "Junio", "Julio"), 1, "Idiomas"),
        Pregunta("Mes 'December' es...", listOf("Noviembre", "Diciembre", "Enero", "Octubre"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Frío'?", listOf("Hot", "Cold", "Warm", "Cool"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Calor'?", listOf("Cold", "Hot", "Ice", "Fire"), 1, "Idiomas"),
        Pregunta("Traduce 'Car'", listOf("Avión", "Coche", "Bici", "Tren"), 1, "Idiomas"),
        Pregunta("Traduce 'Bike'", listOf("Coche", "Bicicleta", "Moto", "Patines"), 1, "Idiomas"),
        Pregunta("Objeto 'Pen' es...", listOf("Lápiz", "Pluma/Bolígrafo", "Goma", "Regla"), 1, "Idiomas"),
        Pregunta("Objeto 'Pencil' es...", listOf("Pluma", "Lápiz", "Color", "Marcador"), 1, "Idiomas"),
        Pregunta("Lugar 'City' es...", listOf("Campo", "Ciudad", "Pueblo", "Playa"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Adios'?", listOf("Hello", "Goodbye", "Please", "Thanks"), 1, "Idiomas"),
        Pregunta("¿Cómo se dice 'Por favor'?", listOf("Thanks", "Please", "Sorry", "Excuse me"), 1, "Idiomas"),
        Pregunta("Color 'Pink' es...", listOf("Morado", "Rosa", "Naranja", "Rojo"), 1, "Idiomas"),
        Pregunta("Color 'Orange' es...", listOf("Rojo", "Naranja", "Amarillo", "Café"), 1, "Idiomas"),
        Pregunta("Color 'Purple' es...", listOf("Rosa", "Morado", "Azul", "Negro"), 1, "Idiomas"),

    )

    fun obtenerPreguntaAleatoria(): Pregunta {
        return preguntas.random()
    }
}